#152 Add new command 'import sonarqube <DIR>' to CLI
fga-eps-mds/2022-1-MeasureSoftGram-CLI pull request #2
Opened 2022-07-23 18:09 UTC by lboaventura25

# Mudança tal

## Descrição
Escreva uma breve descrição sobre o que o Pull Request resolve

[Nome da Issue](link_da_issue)

## Porque este Pull Request é necessário?
Descreva o motivo da realização do documento

## Critérios de aceitação
(Exemplos de critérios de aceitação)

1. [ ] Todas as informações necessárias estão presentes?
2. [ ] O documento está escrito de forma concisa?
3. [ ] A ortografia do documento está correta?

Closes #numero_da_issue

2022-07-27 00:30 UTC, durvalcarvalho commented
Boa @lboaventura25! Gostei muito da solução.

Algumas observações:

- Agora que a pré-configuração foi desacionada da coleta de métricas podemos tirar o parâmetro `id` do comando `import`.
- Na nossa API não diferenciamos (e nem sei se isso é ou não é um requisito) as métricas de acordo com a `language_extension`, eu acho que seria uma boa ideia tirar esse parâmetro também.

Em resumo, o que impede de usarmos o comando da seguinte maneira `measuresoftgram import sonarqube tmp-sonar/`?

2022-07-27 00:33 UTC, durvalcarvalho requested changes
Boa @lboaventura25! Gostei muito da solução.

Algumas observações:

- Agora que a pré-configuração foi desassociada da coleta de métricas podemos tirar o parâmetro `id` do comando `import`.
- Na nossa API não diferenciamos as métricas de acordo com a `language_extension`, eu acho que seria uma boa ideia tirar esse parâmetro também. 

Um TODO é validar essa questão de associar as métricas com a linguagem de programação. Atualmente não fazemos isso e nem temos isso mapeado no nosso roadmap.

Em resumo, o que impede de usarmos o comando da seguinte maneira `measuresoftgram import sonarqube tmp-sonar/`?

2022-07-28 14:06 UTC, lboaventura25 commented
@durvalcarvalho obrigado pelas colocações!

* Sobre o primeiro ponto será feito a exclusão do argumento do ID da pré configuração.
* Sobre o segundo ponto não será possível disassociar o repositório da language_extension por causa das checagens que existem no `Core`.

2022-07-29 00:16 UTC, durvalcarvalho approved these changes
Excelente solução!

2022-07-29 00:17 UTC, merged