285 fix endpoint error on CLI
fga-eps-mds/2022-1-MeasureSoftGram-CLI pull request #6
Opened 2022-09-09 14:25 UTC by danieldagerom

# Erro com Endpoint na CLI

## Descrição
Esse PR resolve a issue #285, onde há um problema com o endpoint na CLI, no qual foi adicionado mais um nível na url, o `/produc_id`

[Erro com Endpoint na CLI](https://github.com/fga-eps-mds/2022-1-MeasureSoftGram-Doc/issues/285)

## Porque este Pull Request é necessário?
Para que seja possível rodar a CLI com os comandos atuais.

## Critérios de aceitação

1. [ ] A CLI funciona adequadamente.

2022-09-09 17:10 UTC, lboaventura25 commented
@danieldagerom foi mexido em um arquivo parser.py que é utilizado para coketar as métricas do sonarqube, tem algum motivo?

A branch está desatualizada com a develop.

Os testes, lint e build estão quebrando.

Assim que arrumar essas coisas posso reavaliar o PR

2022-09-09 20:12 UTC, danieldagerom commented
@lboaventura25 os testes, lint e build estão funcionando corretamente agora, e a branch está atualizada com a develop. Pode refazer sua avaliação, por favor? :)

2022-09-09 22:01 UTC, herickport requested changes

2022-09-09 22:01 UTC, herickport commented on src/cli/commands/parse_get_entity/parse_get_entity.py
> +        f'products/3/'
Acho que seja interessante vc adicionar o `product_id` como um argumento do comando `get` tbm (assim como `organization_id` e `repositoriy_id`) pra não ficar hard-coded aqui e o usuário conseguir alterar

2022-09-10 14:14 UTC, danieldagerom commented on src/cli/commands/parse_get_entity/parse_get_entity.py
> +        f'products/3/'
Entendi, @herickport. Vou resolver isso.

2022-09-10 17:26 UTC, merged